-- ========================
-- SOYO 프로젝트: Oracle DDL + COMMENT 통합 파일
-- 작성자: 고승범
-- ========================

-- 테이블 삭제
DROP TABLE RECENT_VIEW;
DROP TABLE PRODUCT_SIZE;
DROP TABLE PRODUCT;
DROP TABLE ORDER_DETAIL;
DROP TABLE TB_LIKE;
DROP TABLE DELIVERY_ADDRESS;
DROP TABLE WISH_LIST;
DROP TABLE CART;
DROP TABLE TB_ORDER;
DROP TABLE REVIEW;
DROP TABLE NOTICE;
DROP TABLE MEMBER;

-- 테이블 생성
CREATE TABLE RECENT_VIEW (
  VIEW_DATE DATE DEFAULT SYSDATE,
  MEMBER_ID VARCHAR2(20) NOT NULL,
  PRODUCT_NO NUMBER
);

CREATE TABLE PRODUCT_SIZE (
  PRODUCT_SIZE_NO NUMBER PRIMARY KEY,
  SIZE VARCHAR2(1)
);

CREATE TABLE PRODUCT (
  PRODUCT_NO NUMBER PRIMARY KEY,
  PRODUCT_NAME VARCHAR2(200),
  PRODUCT_PRICE NUMBER,
  PRODUCT_CATEGORY VARCHAR2(15) NOT NULL,
  PRODUCT_CATION VARCHAR2(300),
  PRODUCT_SUB_CAPTION CLOB,
  PRODUCT_ORIGIN VARCHAR2(300),
  PRODUCT_CHANGE VARCHAR2(300) NOT NULL,
  PRODUCT_COUNT NUMBER DEFAULT 0,
  PRODUCT_REGISTERED_DATE DATE DEFAULT SYSDATE,
  STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y','N')),
  PRODUCT_SIZE_NO NUMBER
);

CREATE TABLE ORDER_DETAIL (
  ORDER_DETAIL_NO NUMBER PRIMARY KEY,
  PRODUCT_AMOUNT NUMBER,
  ORDER_NO NUMBER NOT NULL,
  PRODUCT_NO NUMBER
);

CREATE TABLE TB_LIKE (
  REVIEW_NO NUMBER,
  MEMBER_ID VARCHAR2(20) NOT NULL
);

CREATE TABLE DELIVERY_ADDRESS (
  ADDRESS_NO NUMBER PRIMARY KEY,
  ADDRESS_NAME VARCHAR2(30) NOT NULL,
  ADDRESS_OTHER VARCHAR2(200) NOT NULL,
  IS_DEFAULT CHAR(1) DEFAULT 'N',
  RECEIVER_NAME VARCHAR2(10),
  RECEIVER_PHONE VARCHAR2(30),
  MEMBER_ID VARCHAR2(20) NOT NULL
);

CREATE TABLE WISH_LIST (
  MEMBER_ID VARCHAR2(20) NOT NULL,
  PRODUCT_NO NUMBER
);

CREATE TABLE CART (
  CART_NO NUMBER PRIMARY KEY,
  PRODUCT_COUNT NUMBER,
  CART_ENROLLDATE DATE DEFAULT SYSDATE,
  MEMBER_ID VARCHAR2(20) NOT NULL,
  PRODUCT_NO NUMBER
);

CREATE TABLE TB_ORDER (
  ORDER_NO NUMBER PRIMARY KEY,
  TOTAL_PRICE NUMBER NOT NULL,
  RECEIVER_NAME VARCHAR2(50),
  RECEIVER_PHONE VARCHAR2(20),
  REQUEST_MSG VARCHAR2(1000),
  DELIVERY_DATE DATE,
  CANCEL_DATE DATE,
  ORDER_DATE DATE NOT NULL,
  ORDER_STATUS VARCHAR2(20) DEFAULT '주문완료',
  MEMBER_ID VARCHAR2(20) NOT NULL
);

CREATE TABLE REVIEW (
  REVIEW_NO NUMBER PRIMARY KEY,
  REVIEW_TITLE VARCHAR2(200) NOT NULL,
  REVIEW_CONTENT VARCHAR2(4000),
  RATING NUMBER,
  REVIEW_THUMBNAIL_ORIGIN VARCHAR2(200),
  REVIEW_THUMBNAIL_CHANGE VARCHAR2(200) NOT NULL,
  REVIEW_DATE DATE NOT NULL,
  STATUS CHAR(3) DEFAULT 'N',
  PRODUCT_NO NUMBER,
  MEMBER_ID VARCHAR2(20) NOT NULL
);

CREATE TABLE NOTICE (
  NOTICE_NO NUMBER PRIMARY KEY,
  NOTICE_TITLE VARCHAR2(200),
  NOTICE_CONTENT VARCHAR2(200),
  NOTICE_DATE DATE,
  STATUS CHAR(1)
);

CREATE TABLE MEMBER (
  MEMBER_ID VARCHAR2(20) PRIMARY KEY,
  MEMBER_PWD VARCHAR2(20) NOT NULL,
  MEMBER_NAME VARCHAR2(18) NOT NULL,
  GENDER VARCHAR2(1),
  BIRTH_DATE DATE NOT NULL,
  EMAIL VARCHAR2(30) NOT NULL,
  PHONE VARCHAR2(11) NOT NULL,
  ADDRESS VARCHAR2(150) NOT NULL,
  ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS CHAR(3) DEFAULT 'Y' CHECK (STATUS IN ('Y','N')) NOT NULL
);

-- ========================
-- 테이블 COMMENT 전체 추가
-- ========================

-- MEMBER 테이블
COMMENT ON TABLE MEMBER IS '회원 정보 테이블';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디 (영문, 숫자 포함 6자 이상)';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원 비밀번호 (영문, 숫자, 특수문자 포함 8자 이상)';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원 이름 (최대 6글자)';
COMMENT ON COLUMN MEMBER.GENDER IS '회원 성별 (M 또는 F)';
COMMENT ON COLUMN MEMBER.BIRTH_DATE IS '회원 생년월일';
COMMENT ON COLUMN MEMBER.EMAIL IS '회원 이메일 주소';
COMMENT ON COLUMN MEMBER.PHONE IS '회원 연락처 (숫자만 11자리)';
COMMENT ON COLUMN MEMBER.ADDRESS IS '회원 기본 배송지 주소';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MEMBER.STATUS IS '회원 상태 (Y: 활성, N: 탈퇴)';

-- PRODUCT 테이블
COMMENT ON TABLE PRODUCT IS '상품 정보 테이블';
COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '상품 번호 (자동 증가)';
COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '상품 이름';
COMMENT ON COLUMN PRODUCT.PRODUCT_PRICE IS '상품 가격 (100 단위 정수)';
COMMENT ON COLUMN PRODUCT.PRODUCT_CATEGORY IS '상품 카테고리 (남자, 여자, 아동, 악세사리)';
COMMENT ON COLUMN PRODUCT.PRODUCT_CATION IS '상품 태그 설명';
COMMENT ON COLUMN PRODUCT.PRODUCT_SUB_CAPTION IS '상품 상세 설명 (Quill, Summernote 등)';
COMMENT ON COLUMN PRODUCT.PRODUCT_ORIGIN IS '상품 원본 이미지';
COMMENT ON COLUMN PRODUCT.PRODUCT_CHANGE IS '상품 변경 이미지';
COMMENT ON COLUMN PRODUCT.PRODUCT_COUNT IS '상품 재고 수량';
COMMENT ON COLUMN PRODUCT.PRODUCT_REGISTERED_DATE IS '상품 등록일';
COMMENT ON COLUMN PRODUCT.STATUS IS '상품 상태 (Y: 사용, N: 미사용)';
COMMENT ON COLUMN PRODUCT.PRODUCT_SIZE_NO IS '사이즈 식별번호';

-- PRODUCT_SIZE 테이블
COMMENT ON TABLE PRODUCT_SIZE IS '상품 사이즈 코드 테이블';
COMMENT ON COLUMN PRODUCT_SIZE.PRODUCT_SIZE_NO IS '상품 사이즈 코드 번호';
COMMENT ON COLUMN PRODUCT_SIZE.SIZE IS '사이즈 (S/M/L)';

-- ORDER 테이블
COMMENT ON TABLE TB_ORDER IS '주문 정보 테이블';
COMMENT ON COLUMN TB_ORDER.ORDER_NO IS '주문 고유번호';
COMMENT ON COLUMN TB_ORDER.TOTAL_PRICE IS '전체 주문 금액';
COMMENT ON COLUMN TB_ORDER.RECEIVER_NAME IS '수령인 이름';
COMMENT ON COLUMN TB_ORDER.RECEIVER_PHONE IS '수령인 연락처';
COMMENT ON COLUMN TB_ORDER.REQUEST_MSG IS '배송 요청사항';
COMMENT ON COLUMN TB_ORDER.DELIVERY_DATE IS '배송 완료일자';
COMMENT ON COLUMN TB_ORDER.CANCEL_DATE IS '주문 취소일자';
COMMENT ON COLUMN TB_ORDER.ORDER_DATE IS '주문일자';
COMMENT ON COLUMN TB_ORDER.ORDER_STATUS IS '주문 상태 (주문완료, 결제완료, 배송중, 취소)';
COMMENT ON COLUMN TB_ORDER.MEMBER_ID IS '회원 아이디';

-- ORDER_DETAIL 테이블
COMMENT ON TABLE ORDER_DETAIL IS '주문 상세 정보 테이블';
COMMENT ON COLUMN ORDER_DETAIL.ORDER_DETAIL_NO IS '주문 상세 고유번호';
COMMENT ON COLUMN ORDER_DETAIL.PRODUCT_AMOUNT IS '주문 수량';
COMMENT ON COLUMN ORDER_DETAIL.ORDER_NO IS '주문 번호 (외래키)';
COMMENT ON COLUMN ORDER_DETAIL.PRODUCT_NO IS '상품 번호 (외래키)';

-- REVIEW 테이블
COMMENT ON TABLE REVIEW IS '상품 리뷰 테이블';
COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰 번호';
COMMENT ON COLUMN REVIEW.REVIEW_TITLE IS '리뷰 제목';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '리뷰 내용';
COMMENT ON COLUMN REVIEW.RATING IS '평점 (1~5)';
COMMENT ON COLUMN REVIEW.REVIEW_THUMBNAIL_ORIGIN IS '썸네일 원본 파일명';
COMMENT ON COLUMN REVIEW.REVIEW_THUMBNAIL_CHANGE IS '썸네일 저장 파일명';
COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '리뷰 작성일';
COMMENT ON COLUMN REVIEW.STATUS IS '게시 여부 (Y/N)';
COMMENT ON COLUMN REVIEW.PRODUCT_NO IS '상품 번호';
COMMENT ON COLUMN REVIEW.MEMBER_ID IS '회원 아이디';

-- TB_LIKE 테이블
COMMENT ON TABLE TB_LIKE IS '리뷰 좋아요 테이블';
COMMENT ON COLUMN TB_LIKE.REVIEW_NO IS '리뷰 번호';
COMMENT ON COLUMN TB_LIKE.MEMBER_ID IS '회원 아이디';

-- NOTICE 테이블
COMMENT ON TABLE NOTICE IS '공지사항 테이블';
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지 고유번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지 제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지 내용';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '작성일자';
COMMENT ON COLUMN NOTICE.STATUS IS '공지 상태';

-- CART 테이블
COMMENT ON TABLE CART IS '장바구니 테이블';
COMMENT ON COLUMN CART.CART_NO IS '장바구니 번호';
COMMENT ON COLUMN CART.PRODUCT_COUNT IS '상품 수량';
COMMENT ON COLUMN CART.CART_ENROLLDATE IS '장바구니 담은 날짜';
COMMENT ON COLUMN CART.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN CART.PRODUCT_NO IS '상품 번호';

-- WISH_LIST 테이블
COMMENT ON TABLE WISH_LIST IS '찜 목록 테이블';
COMMENT ON COLUMN WISH_LIST.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN WISH_LIST.PRODUCT_NO IS '상품 번호';

-- DELIVERY_ADDRESS 테이블
COMMENT ON TABLE DELIVERY_ADDRESS IS '회원 배송지 테이블';
COMMENT ON COLUMN DELIVERY_ADDRESS.ADDRESS_NO IS '배송지 번호';
COMMENT ON COLUMN DELIVERY_ADDRESS.ADDRESS_NAME IS '배송지 이름';
COMMENT ON COLUMN DELIVERY_ADDRESS.ADDRESS_OTHER IS '배송지 상세 주소';
COMMENT ON COLUMN DELIVERY_ADDRESS.IS_DEFAULT IS '기본 배송지 여부 (Y/N)';
COMMENT ON COLUMN DELIVERY_ADDRESS.RECEIVER_NAME IS '수령인 이름';
COMMENT ON COLUMN DELIVERY_ADDRESS.RECEIVER_PHONE IS '수령인 연락처';
COMMENT ON COLUMN DELIVERY_ADDRESS.MEMBER_ID IS '회원 아이디';

-- RECENT_VIEW 테이블
COMMENT ON TABLE RECENT_VIEW IS '최근 본 상품 테이블';
COMMENT ON COLUMN RECENT_VIEW.VIEW_DATE IS '조회일자';
COMMENT ON COLUMN RECENT_VIEW.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN RECENT_VIEW.PRODUCT_NO IS '상품 번호';

-- ========================
-- SEQUENCE 생성문
-- ========================

-- 테이블별 시퀀스 생성
CREATE SEQUENCE SEQ_PRODUCT_SIZE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_DETAIL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DELIVERY_ADDRESS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CART START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;




CREATE TABLE PRODUCT_SIZE (
  PRODUCT_SIZE_NO NUMBER PRIMARY KEY,
  SIZE_CODE VARCHAR2(1)
);

COMMENT ON TABLE PRODUCT_SIZE IS '상품 사이즈 코드 테이블';
COMMENT ON COLUMN PRODUCT_SIZE.PRODUCT_SIZE_NO IS '상품 사이즈 코드 번호';
COMMENT ON COLUMN PRODUCT_SIZE.SIZE_CODE IS '사이즈 (S/M/L)';

COMMIT;