SELECT NOTICE_NO
     , NOTICE_TITLE
     , NOTICE_DATE
     , STATUS
  FROM NOTICE
 ORDER BY NOTICE_NO DESC;

SELECT COUNT(*)
  FROM NOTICE;
  
INSERT INTO NOTICE VALUES(1, '제목', '내용', '2025-03-21', 'Y', NULL);
    
INSERT INTO NOTICE VALUES (1, '공지 제목 1', '이것은 공지 내용입니다 1', '2025-03-22', 'Y', NULL);
INSERT INTO NOTICE VALUES (2, '공지 제목 2', '이것은 공지 내용입니다 2', '2025-03-23', 'Y', NULL);
INSERT INTO NOTICE VALUES (3, '공지 제목 3', '이것은 공지 내용입니다 3', '2025-03-25', 'Y', NULL);
INSERT INTO NOTICE VALUES (4, '공지 제목 4', '이것은 공지 내용입니다 4', '2025-03-27', 'Y', NULL);
INSERT INTO NOTICE VALUES (5, '공지 제목 5', '이것은 공지 내용입니다 5', '2025-03-29', 'Y', NULL);
INSERT INTO NOTICE VALUES (6, '공지 제목 6', '이것은 공지 내용입니다 6', '2025-03-30', 'Y', NULL);
INSERT INTO NOTICE VALUES (7, '공지 제목 7', '이것은 공지 내용입니다 7', '2025-04-01', 'Y', NULL);
INSERT INTO NOTICE VALUES (8, '공지 제목 8', '이것은 공지 내용입니다 8', '2025-04-03', 'Y', NULL);
INSERT INTO NOTICE VALUES (9, '공지 제목 9', '이것은 공지 내용입니다 9', '2025-04-04', 'Y', NULL);
INSERT INTO NOTICE VALUES (10, '공지 제목 10', '이것은 공지 내용입니다 10', '2025-04-06', 'Y', NULL);
INSERT INTO NOTICE VALUES (11, '공지 제목 11', '이것은 공지 내용입니다 11', '2025-04-08', 'Y', NULL);
INSERT INTO NOTICE VALUES (12, '공지 제목 12', '이것은 공지 내용입니다 12', '2025-04-09', 'Y', NULL);
INSERT INTO NOTICE VALUES (13, '공지 제목 13', '이것은 공지 내용입니다 13', '2025-04-10', 'Y', NULL);
INSERT INTO NOTICE VALUES (14, '공지 제목 14', '이것은 공지 내용입니다 14', '2025-04-12', 'Y', NULL);
INSERT INTO NOTICE VALUES (15, '공지 제목 15', '이것은 공지 내용입니다 15', '2025-04-14', 'Y', NULL);
INSERT INTO NOTICE VALUES (16, '공지 제목 16', '이것은 공지 내용입니다 16', '2025-04-15', 'Y', NULL);
INSERT INTO NOTICE VALUES (17, '공지 제목 17', '이것은 공지 내용입니다 17', '2025-04-17', 'Y', NULL);
INSERT INTO NOTICE VALUES (18, '공지 제목 18', '이것은 공지 내용입니다 18', '2025-04-18', 'Y', NULL);
INSERT INTO NOTICE VALUES (19, '공지 제목 19', '이것은 공지 내용입니다 19', '2025-04-20', 'Y', NULL);
INSERT INTO NOTICE VALUES (20, '공지 제목 20', '이것은 공지 내용입니다 20', '2025-04-21', 'Y', NULL);
INSERT INTO NOTICE VALUES (21, '공지 제목 21', '이것은 공지 내용입니다 21', '2025-04-23', 'Y', NULL);
INSERT INTO NOTICE VALUES (22, '공지 제목 22', '이것은 공지 내용입니다 22', '2025-04-24', 'Y', NULL);
INSERT INTO NOTICE VALUES (23, '공지 제목 23', '이것은 공지 내용입니다 23', '2025-04-26', 'Y', NULL);
INSERT INTO NOTICE VALUES (24, '공지 제목 24', '이것은 공지 내용입니다 24', '2025-04-28', 'Y', NULL);
INSERT INTO NOTICE VALUES (25, '공지 제목 25', '이것은 공지 내용입니다 25', '2025-04-30', 'Y', NULL);
INSERT INTO NOTICE VALUES (26, '공지 제목 26', '이것은 공지 내용입니다 26', '2025-05-02', 'Y', NULL);
INSERT INTO NOTICE VALUES (27, '공지 제목 27', '이것은 공지 내용입니다 27', '2025-05-04', 'Y', NULL);
INSERT INTO NOTICE VALUES (28, '공지 제목 28', '이것은 공지 내용입니다 28', '2025-05-06', 'Y', NULL);
INSERT INTO NOTICE VALUES (29, '공지 제목 29', '이것은 공지 내용입니다 29', '2025-05-09', 'Y', NULL);
INSERT INTO NOTICE VALUES (30, '공지 제목 30', '이것은 공지 내용입니다 30', '2025-05-11', 'Y', NULL);
INSERT INTO NOTICE VALUES (31, '공지 제목 31', '이것은 공지 내용입니다 31', '2025-05-14', 'Y', NULL);
INSERT INTO NOTICE VALUES (32, '공지 제목 32', '이것은 공지 내용입니다 32', '2025-05-17', 'Y', NULL);
INSERT INTO NOTICE VALUES (33, '공지 제목 33', '이것은 공지 내용입니다 33', '2025-05-20', 'Y', NULL);
INSERT INTO NOTICE VALUES (34, '공지 제목 34', '이것은 공지 내용입니다 34', '2025-05-23', 'Y', NULL);
INSERT INTO NOTICE VALUES (35, '공지 제목 35', '이것은 공지 내용입니다 35', '2025-05-27', 'Y', NULL);

INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, GENDER, BIRTH_DATE, EMAIL, PHONE, ADDRESS, ENROLL_DATE, STATUS) VALUES 
('user01', 'pwd123', '김철수', 'M', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'user01@example.com', '01012345678', '서울시 강남구 역삼동 123', TO_DATE('2023-01-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user02', 'pwd234', '이영희', 'F', TO_DATE('1988-05-15', 'YYYY-MM-DD'), 'user02@example.com', '01023456789', '부산시 해운대구 우동 456', TO_DATE('2023-02-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user03', 'pwd345', '박지민', 'M', TO_DATE('1995-03-22', 'YYYY-MM-DD'), 'user03@example.com', '01034567890', '대구시 수성구 범어동 789', TO_DATE('2023-03-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user04', 'pwd456', '최유리', 'F', TO_DATE('1992-07-10', 'YYYY-MM-DD'), 'user04@example.com', '01045678901', '인천시 연수구 송도동 321', TO_DATE('2023-04-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user05', 'pwd567', '정우성', 'M', TO_DATE('1987-12-25', 'YYYY-MM-DD'), 'user05@example.com', '01056789012', '광주시 북구 용봉동 654', TO_DATE('2023-05-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user06', 'pwd678', '한지민', 'F', TO_DATE('1993-11-11', 'YYYY-MM-DD'), 'user06@example.com', '01067890123', '대전시 서구 둔산동 987', TO_DATE('2023-06-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user07', 'pwd789', '송강', 'M', TO_DATE('1996-08-08', 'YYYY-MM-DD'), 'user07@example.com', '01078901234', '울산시 남구 삼산동 147', TO_DATE('2023-07-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user08', 'pwd890', '신세경', 'F', TO_DATE('1991-09-09', 'YYYY-MM-DD'), 'user08@example.com', '01089012345', '제주시 애월읍 고내리 258', TO_DATE('2023-08-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user09', 'pwd901', '강다니엘', 'M', TO_DATE('1997-12-12', 'YYYY-MM-DD'), 'user09@example.com', '01090123456', '세종시 도움4로 100', TO_DATE('2023-09-01', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES 
('user10', 'pwd012', '수지', 'F', TO_DATE('1994-10-10', 'YYYY-MM-DD'), 'user10@example.com', '01001234567', '춘천시 석사동 777', TO_DATE('2023-10-01', 'YYYY-MM-DD'), 'Y');



INSERT INTO MEMBER VALUES ('user11', 'pw1111', '임지민', 'M', TO_DATE('1990-02-02', 'YYYY-MM-DD'), 'user11@site.com', '01011112222', '서울시 은평구', TO_DATE('2023-01-11', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user12', 'pw2222', '홍윤아', 'F', TO_DATE('1991-04-03', 'YYYY-MM-DD'), 'user12@site.com', '01022223333', '부산시 남구', TO_DATE('2023-01-12', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user13', 'pw3333', '김민수', 'M', TO_DATE('1989-06-04', 'YYYY-MM-DD'), 'user13@site.com', '01033334444', '광주시 서구', TO_DATE('2023-01-13', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user14', 'pw4444', '이서진', 'M', TO_DATE('1992-08-05', 'YYYY-MM-DD'), 'user14@site.com', '01044445555', '인천시 계양구', TO_DATE('2023-01-14', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user15', 'pw5555', '박보검', 'M', TO_DATE('1993-10-06', 'YYYY-MM-DD'), 'user15@site.com', '01055556666', '수원시 팔달구', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user16', 'pw6666', '전지현', 'F', TO_DATE('1985-12-07', 'YYYY-MM-DD'), 'user16@site.com', '01066667777', '안양시 동안구', TO_DATE('2023-01-16', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user17', 'pw7777', '유아인', 'M', TO_DATE('1986-03-08', 'YYYY-MM-DD'), 'user17@site.com', '01077778888', '성남시 수정구', TO_DATE('2023-01-17', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user18', 'pw8888', '김태희', 'F', TO_DATE('1980-05-09', 'YYYY-MM-DD'), 'user18@site.com', '01088889999', '용인시 기흥구', TO_DATE('2023-01-18', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user19', 'pw9999', '소지섭', 'M', TO_DATE('1979-07-10', 'YYYY-MM-DD'), 'user19@site.com', '01099990000', '천안시 서북구', TO_DATE('2023-01-19', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user20', 'pw0000', '이지은', 'F', TO_DATE('1993-09-11', 'YYYY-MM-DD'), 'user20@site.com', '01000001111', '청주시 흥덕구', TO_DATE('2023-01-20', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES ('user21', 'pwaaaa', '하정우', 'M', TO_DATE('1978-06-12', 'YYYY-MM-DD'), 'user21@site.com', '01022224444', '전주시 완산구', TO_DATE('2023-01-21', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user22', 'pwbbbb', '문채원', 'F', TO_DATE('1986-08-13', 'YYYY-MM-DD'), 'user22@site.com', '01033335555', '원주시 단구동', TO_DATE('2023-01-22', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user23', 'pwcccc', '정해인', 'M', TO_DATE('1988-10-14', 'YYYY-MM-DD'), 'user23@site.com', '01044446666', '경주시 황성동', TO_DATE('2023-01-23', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user24', 'pwdddd', '이하늬', 'F', TO_DATE('1983-12-15', 'YYYY-MM-DD'), 'user24@site.com', '01055557777', '포항시 남구', TO_DATE('2023-01-24', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user25', 'pweeee', '이민호', 'M', TO_DATE('1987-02-16', 'YYYY-MM-DD'), 'user25@site.com', '01066668888', '김해시 삼계동', TO_DATE('2023-01-25', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user26', 'pwffff', '이보영', 'F', TO_DATE('1979-04-17', 'YYYY-MM-DD'), 'user26@site.com', '01077779999', '아산시 배방읍', TO_DATE('2023-01-26', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user27', 'pwg123', '장기용', 'M', TO_DATE('1991-06-18', 'YYYY-MM-DD'), 'user27@site.com', '01088880000', '순천시 연향동', TO_DATE('2023-01-27', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user28', 'pwh456', '김소현', 'F', TO_DATE('1999-08-19', 'YYYY-MM-DD'), 'user28@site.com', '01099991111', '여수시 학동', TO_DATE('2023-01-28', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user29', 'pwi789', '도경수', 'M', TO_DATE('1993-10-20', 'YYYY-MM-DD'), 'user29@site.com', '01000002222', '목포시 상동', TO_DATE('2023-01-29', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user30', 'pwj000', '강소라', 'F', TO_DATE('1990-12-21', 'YYYY-MM-DD'), 'user30@site.com', '01011113333', '창원시 성산구', TO_DATE('2023-01-30', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES ('user31', 'pwaaaa', '김해진', 'M', TO_DATE('1994-03-12', 'YYYY-MM-DD'), 'user31@site.com', '01011113344', '서울시 강동구', TO_DATE('2023-01-20', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user32', 'pwbbbb', '박민지', 'F', TO_DATE('1995-05-24', 'YYYY-MM-DD'), 'user32@site.com', '01022224455', '대구시 북구', TO_DATE('2023-03-15', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user33', 'pwcccc', '이건우', 'M', TO_DATE('1992-09-18', 'YYYY-MM-DD'), 'user33@site.com', '01033335566', '부산시 해운대구', TO_DATE('2023-03-28', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user34', 'pwdddd', '최서윤', 'F', TO_DATE('1996-02-05', 'YYYY-MM-DD'), 'user34@site.com', '01044446677', '광주시 북구', TO_DATE('2023-04-10', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user35', 'pweeee', '정우석', 'M', TO_DATE('1991-08-14', 'YYYY-MM-DD'), 'user35@site.com', '01055557788', '인천시 부평구', TO_DATE('2023-05-12', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user36', 'pwffff', '오지현', 'F', TO_DATE('1993-12-01', 'YYYY-MM-DD'), 'user36@site.com', '01066668899', '전주시 덕진구', TO_DATE('2023-06-22', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user37', 'pwg000', '장민호', 'M', TO_DATE('1990-04-30', 'YYYY-MM-DD'), 'user37@site.com', '01077779900', '원주시 태장동', TO_DATE('2023-07-05', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user38', 'pwh111', '신예림', 'F', TO_DATE('1998-06-11', 'YYYY-MM-DD'), 'user38@site.com', '01088880011', '포항시 북구', TO_DATE('2023-07-19', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user39', 'pwi222', '배승우', 'M', TO_DATE('1995-11-25', 'YYYY-MM-DD'), 'user39@site.com', '01099991122', '창원시 의창구', TO_DATE('2023-08-09', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user40', 'pwj333', '홍채은', 'F', TO_DATE('1999-01-17', 'YYYY-MM-DD'), 'user40@site.com', '01000002233', '용인시 수지구', TO_DATE('2023-09-14', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user41', 'pwk444', '서재원', 'M', TO_DATE('1989-07-22', 'YYYY-MM-DD'), 'user41@site.com', '01011113355', '청주시 상당구', TO_DATE('2023-10-07', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user42', 'pwl555', '이주희', 'F', TO_DATE('1996-10-02', 'YYYY-MM-DD'), 'user42@site.com', '01022224466', '고양시 일산동구', TO_DATE('2023-10-21', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user43', 'pwm666', '남도현', 'M', TO_DATE('1992-03-13', 'YYYY-MM-DD'), 'user43@site.com', '01033335577', '수원시 영통구', TO_DATE('2023-11-03', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user44', 'pwn777', '유다연', 'F', TO_DATE('1988-05-30', 'YYYY-MM-DD'), 'user44@site.com', '01044446688', '안산시 단원구', TO_DATE('2023-11-28', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user45', 'pwo888', '황건희', 'M', TO_DATE('1997-09-09', 'YYYY-MM-DD'), 'user45@site.com', '01055557799', '세종시 반곡동', TO_DATE('2023-12-10', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user46', 'pwp999', '방시윤', 'F', TO_DATE('1993-03-03', 'YYYY-MM-DD'), 'user46@site.com', '01066668800', '김포시 고촌읍', TO_DATE('2023-12-21', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user47', 'pwq000', '임현수', 'M', TO_DATE('1994-06-06', 'YYYY-MM-DD'), 'user47@site.com', '01077779911', '평택시 동삭동', TO_DATE('2024-01-08', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user48', 'pwr111', '정수지', 'F', TO_DATE('1992-02-27', 'YYYY-MM-DD'), 'user48@site.com', '01088880022', '의정부시 민락동', TO_DATE('2024-01-29', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user49', 'pws222', '김재민', 'M', TO_DATE('1991-11-11', 'YYYY-MM-DD'), 'user49@site.com', '01099991133', '하남시 덕풍동', TO_DATE('2024-03-05', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user50', 'pwt333', '조다인', 'F', TO_DATE('1999-08-07', 'YYYY-MM-DD'), 'user50@site.com', '01000002244', '군포시 금정동', TO_DATE('2024-03-22', 'YYYY-MM-DD'), 'Y');

INSERT INTO MEMBER VALUES ('user51', 'pwu444', '정태우', 'M', TO_DATE('1990-05-23', 'YYYY-MM-DD'), 'user51@site.com', '01011114455', '성남시 중원구', TO_DATE('2024-04-03', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user52', 'pwv555', '박서연', 'F', TO_DATE('1997-10-01', 'YYYY-MM-DD'), 'user52@site.com', '01022225566', '천안시 동남구', TO_DATE('2024-04-19', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user53', 'pww666', '강수현', 'M', TO_DATE('1996-07-04', 'YYYY-MM-DD'), 'user53@site.com', '01033336677', '이천시 중리동', TO_DATE('2024-05-22', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user54', 'pwx777', '윤나리', 'F', TO_DATE('1993-03-29', 'YYYY-MM-DD'), 'user54@site.com', '01044447788', '광명시 하안동', TO_DATE('2024-06-10', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user55', 'pwy888', '홍민준', 'M', TO_DATE('1989-06-26', 'YYYY-MM-DD'), 'user55@site.com', '01055558899', '제주시 노형동', TO_DATE('2024-06-28', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user56', 'pwz999', '김다솜', 'F', TO_DATE('1994-12-13', 'YYYY-MM-DD'), 'user56@site.com', '01066669900', '서귀포시 중문동', TO_DATE('2024-07-01', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user57', 'pwaa00', '이현우', 'M', TO_DATE('1995-11-04', 'YYYY-MM-DD'), 'user57@site.com', '01077770011', '춘천시 석사동', TO_DATE('2024-07-19', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user58', 'pwbb11', '전유진', 'F', TO_DATE('1992-02-11', 'YYYY-MM-DD'), 'user58@site.com', '01088881122', '경산시 정평동', TO_DATE('2024-08-05', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user59', 'pwcc22', '노하늘', 'M', TO_DATE('1997-01-08', 'YYYY-MM-DD'), 'user59@site.com', '01099992233', '울산시 중구', TO_DATE('2024-08-17', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user60', 'pwdd33', '차지은', 'F', TO_DATE('1988-04-15', 'YYYY-MM-DD'), 'user60@site.com', '01000003344', '안양시 만안구', TO_DATE('2024-09-03', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user61', 'pwee44', '오세훈', 'M', TO_DATE('1996-08-20', 'YYYY-MM-DD'), 'user61@site.com', '01011114466', '천안시 성환읍', TO_DATE('2024-09-18', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user62', 'pwff55', '조민아', 'F', TO_DATE('1994-05-10', 'YYYY-MM-DD'), 'user62@site.com', '01022225577', '서울시 중랑구', TO_DATE('2024-10-05', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user63', 'pwgf66', '이승재', 'M', TO_DATE('1987-09-28', 'YYYY-MM-DD'), 'user63@site.com', '01033336688', '대전시 유성구', TO_DATE('2024-10-21', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user64', 'pwhh77', '한지호', 'F', TO_DATE('1999-11-12', 'YYYY-MM-DD'), 'user64@site.com', '01044447799', '성남시 분당구', TO_DATE('2024-11-03', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user65', 'pwij88', '윤주성', 'M', TO_DATE('1992-01-25', 'YYYY-MM-DD'), 'user65@site.com', '01055558800', '서울시 마포구', TO_DATE('2024-11-18', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user66', 'pwkk99', '백하린', 'F', TO_DATE('1993-10-06', 'YYYY-MM-DD'), 'user66@site.com', '01066669911', '광주시 남구', TO_DATE('2024-12-01', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user67', 'pwll00', '민지후', 'M', TO_DATE('1991-07-19', 'YYYY-MM-DD'), 'user67@site.com', '01077770022', '서울시 동작구', TO_DATE('2024-12-23', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user68', 'pwmn11', '장예슬', 'F', TO_DATE('1989-12-30', 'YYYY-MM-DD'), 'user68@site.com', '01088881133', '구미시 도량동', TO_DATE('2025-01-08', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user69', 'pwnp22', '고은우', 'M', TO_DATE('1998-09-07', 'YYYY-MM-DD'), 'user69@site.com', '01099992244', '서울시 은평구', TO_DATE('2025-01-22', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user70', 'pwoq33', '유민아', 'F', TO_DATE('1997-03-01', 'YYYY-MM-DD'), 'user70@site.com', '01000003355', '제주시 구좌읍', TO_DATE('2025-03-04', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user71', 'pwrq44', '신태영', 'M', TO_DATE('1994-01-18', 'YYYY-MM-DD'), 'user71@site.com', '01011114477', '경주시 용강동', TO_DATE('2025-04-02', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user72', 'pwsr55', '남보라', 'F', TO_DATE('1993-06-30', 'YYYY-MM-DD'), 'user72@site.com', '01022225588', '목포시 하당동', TO_DATE('2025-04-17', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user73', 'pwst66', '윤동하', 'M', TO_DATE('1996-10-03', 'YYYY-MM-DD'), 'user73@site.com', '01033336699', '서울시 관악구', TO_DATE('2025-05-01', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user74', 'pwsu77', '심예원', 'F', TO_DATE('1990-08-22', 'YYYY-MM-DD'), 'user74@site.com', '01044447700', '수원시 권선구', TO_DATE('2025-05-19', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user75', 'pwsz88', '하현우', 'M', TO_DATE('1988-12-15', 'YYYY-MM-DD'), 'user75@site.com', '01055558811', '김천시 율곡동', TO_DATE('2025-06-04', 'YYYY-MM-DD'), 'Y');
INSERT INTO MEMBER VALUES ('user76', 'pwsz99', '안혜민', 'F', TO_DATE('1995-04-14', 'YYYY-MM-DD'), 'user76@site.com', '01066669922', '남양주시 별내동', TO_DATE('2025-06-07', 'YYYY-MM-DD'), 'Y');


COMMIT

DROP TABLE MEMBER

CREATE TABLE MEMBER (
  MEMBER_ID VARCHAR2(20) PRIMARY KEY,
  MEMBER_PWD VARCHAR2(20) NOT NULL,
  MEMBER_NAME VARCHAR2(18) NOT NULL,
  GENDER VARCHAR2(1),
  BIRTH_DATE DATE NOT NULL,
  EMAIL VARCHAR2(30) NOT NULL,
  PHONE VARCHAR2(11) NOT NULL,
  ADDRESS VARCHAR2(150) NOT NULL,
  ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y','N')) NOT NULL
);



COMMENT ON TABLE MEMBER IS '회원 정보 테이블';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디 (영문, 숫자 포함 6자 이상)';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원 비밀번호 (영문, 숫자, 특수문자 포함 8자 이상)';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원 이름 (최대 6글자)';
COMMENT ON COLUMN MEMBER.GENDER IS '회원 성별 (M 또는 F)';
COMMENT ON COLUMN MEMBER.BIRTH_DATE IS '회원 생년월일';
COMMENT ON COLUMN MEMBER.EMAIL IS '회원 이메일 주소';
COMMENT ON COLUMN MEMBER.PHONE IS '회원 연락처 (숫자만 11자리)';
COMMENT ON COLUMN MEMBER.ADDRESS IS '회원 기본 배송지 주소';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MEMBER.STATUS IS '회원 상태 (Y: 활성, N: 탈퇴)';

UPDATE MEMBER
   SET STATUS = 'N'
 WHERE MEMBER_ID = 
   AND STATUS = 'Y'

SELECT *
  FROM MEMBER
 WHERE MEMBER_ID =  'user02'
 
 
 
UPDATE MEMBER
   SET MEMBER_NAME = '김갑생'
     , GENDER = 'F'
     , BIRTH_DATE = '1989-10-01'
     , EMAIL = 'user02@example.com'
     , PHONE = '01041839810'
     , ADDRESS = '제주도 을령군'
  WHERE MEMBER_ID = 'user02'


SELECT NOTICE_NO
     , NOTICE_TITLE
     , NOTICE_CONTENT
     , NOTICE_DATE 
     , NOTICE_IMAGE
  FROM NOTICE
 WHERE NOTICE_NO = 1 
 
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL
                          , ?
                          , ?
                          , ?
                          , NULL
                          , ?
                          , ?
                          , ?
                          , SYSDATE
                          , 'Y')
 
INSERT INTO PRODUCT_SIZE VALUES (SEQ_PRODUCT_SIZE.NEXTVAL
                                , SEQ_PRODUCT.CURRVAL
                                , ?
                                , ?)
                                
                                
 		SELECT COUNT(*)
 		  FROM PRODUCT
 		 WHERE PRODUCT_NAME LIKE '%상품%'

	SELECT PRODUCT_NO,
 			   PRODUCT_NAME,
 			   PRODUCT_PRICE,
 			   PRODUCT_CATEGORY,
 			   PRODUCT_CAPTION,
 			   PRODUCT_ORIGIN,
 			   PRODUCT_CHANGE,
 			   STATUS
 		FROM PRODUCT
 	   WHERE PRODUCT_NAME LIKE '%3%'
 	   ORDER BY PRODUCT_NO DESC 



SELECT 
    P.PRODUCT_NO,
    P.PRODUCT_NAME,
    P.PRODUCT_PRICE,
    P.PRODUCT_CATEGORY,
    P.PRODUCT_CAPTION,
    P.PRODUCT_ORIGIN,
    P.PRODUCT_CHANGE,
    P.STATUS,
    P.PRODUCT_SUB_CAPTION,
    PS.STOCK_COUNT
FROM PRODUCT P
JOIN PRODUCT_SIZE PS ON P.PRODUCT_NO = PS.PRODUCT_NO
WHERE P.PRODUCT_NO = 2
  AND PS.PRODUCT_SIZE = 'L';
  
SELECT 
    P.PRODUCT_NO,
    PS.STOCK_COUNT
FROM PRODUCT P
JOIN PRODUCT_SIZE PS ON P.PRODUCT_NO = PS.PRODUCT_NO
WHERE P.PRODUCT_NO = 2
  AND PS.PRODUCT_SIZE = #{productSize};

DROP TABLE PRODUCT_SIZE

CREATE TABLE PRODUCT_SIZE (
    PRODUCT_NO   NUMBER      NOT NULL,
    PRODUCT_SIZE CHAR(1) NOT NULL,
    STOCK_COUNT  NUMBER,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_NO, PRODUCT_SIZE),
    CONSTRAINT FK_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
          REFERENCES PRODUCT (PRODUCT_NO)
);

INSERT INTO PRODUCT_SIZE VALUES(5, 'M', 3)
COMMIT

UPDATE PRODUCT
   SET PRODUCT_NAME = ?
     , PRODUCT_PRICE = ?
     , PRODUCT_CATEGORY = ?
     , PRODUCT_CATION = ?
     , PRODUCT_SUBCATION = ?
     , PRODUCT_ORIGIN = ?
     , PRODUCT_CHANGE = ?
 WHERE PRODUCT_NO = ?
    
UPDATE PRODUCT_SIZE
   SET STOCK_COUNT = 5
 WHERE PRODUCT_NO = 7
   AND PRODUCT_SIZE = 'M'

COMMIT

SELECT COUNT(*)
  FROM PRODUCT_SIZE
 WHERE PRODUCT_NO = 7
   AND PRODUCT_SIZE = 'M'

SELECT COUNT(*)
  FROM NOTICE
 WHERE NOTICE_TITLE = 

pri
pk proNO
#

pri 
pk proNO
#

 
SELECT REVIEW_NO,
     , REVIEW_TITLE
     , REVIEW_CONTENT
     , RATING
     , REVIEW_DATE
     , MEMBER_ID
     , L.COUNT(*) C
  FROM REVIEW R
  JOIN TB_LIKE L ON (R.REVIEW_NO = L.REVIEW_NO)
 WHERE STATUS = 'Y'
 OREDER BY C DESC
 
DROP SEQUENCE SEQ_PRODUCT
DROP SEQUENCE SEQ_PRODUCT_SIZE
\
ALTER TABLE PRODUCT ADD PRODUCT_SUB_ORIGIN VARCHAR2(300)
ALTER TABLE PRODUCT ADD PRODUCT_TAG VARCHAR2(20)
ALTER TABLE PRODUCT_TAG ADD PRODUCT_TAG_NO NUMBER

SELECT *
   FROM CART
WHERE MEMBER_ID = ?
  AND PRODUCT_NO = ?
  
INSERT INTO PRODUCT_TAG VALUES ()
DROP TABLE PRODUCT_TAG
CREATE TABLE PRODUCT_TAG (
  PRODUCT_NO NUMBER,
  TAG_NAME VARCHAR2(20),
  PRIMARY KEY (PRODUCT_NO, TAG_NAME)

)

SELECT 
    PRODUCT_NO,
    PRODUCT_NAME,
    PRODUCT_PRICE,
    PRODUCT_CATEGORY,
    PRODUCT_ORIGIN,
    PRODUCT_CHANGE,
    STATUS,
    PRODUCT_SUB_CAPTION,
    PRODUCT_CAPTION,
    PRODUCT_SUB_ORIGIN,
    PRODUCT_SUB_CHANGE,
    PRODUCT_TAG
FROM PRODUCT 
WHERE PRODUCT_NO = 12



DELETE 
  FROM PRODUCT_TAG
 WHERE PRODUCT_NO = 15

INSERT INTO PRODUCT_TAG VALUES(15, '원피스')

SELECT TAG_NAME
  FROM PRODUCT_TAG
  WHERE PRODUCT_NO = 15
  

COMMIT

		SELECT REVIEW_NO
			 , REVIEW_TITLE
			 , REVIEW_CONTENT
			 , RATING
			 , REVIEW_THUMBNAIL_ORIGIN 
			 , REVIEW_THUMBNAIL_CHANGE
			 , REVIEW_DATE
			 , R.STATUS
			 , R.PRODUCT_NO
			 , R.MEMBER_ID
             , P.PRODUCT_NAME
             , M.MEMBER_NAME
		  FROM REVIEW R
		  JOIN PRODUCT P ON R.PRODUCT_NO = P.PRODUCT_NO
		  JOIN MEMBER M ON R.MEMBER_ID = M.MEMBER_ID
          
SELECT COUNT(*)
  FROM MEMBER
 WHERE TO_CHAR(ENROLL_DATE, 'YYYYMM') BETWEEN '202301' AND '202303';

SELECT TRUNC(ENROLL_DATE, 'MM') - MOD(TO_NUMBER(TO_CHAR(ENROLL_DATE, 'MM')) - 1, 3) * INTERVAL '1' MONTH AS QUARTER_START,
       COUNT(*) AS TOTAL
  FROM MEMBER
 GROUP BY TRUNC(ENROLL_DATE, 'MM') - MOD(TO_NUMBER(TO_CHAR(ENROLL_DATE, 'MM')) - 1, 3) * INTERVAL '1' MONTH
 ORDER BY QUARTER_START;


DELETE NOTICE;

SELECT COUNT(*)
   FROM PRODUCT
   WHERE PRODUCT_CATEGORY ='여성'
   
SELECT REVIEW_NO
     , REVIEW_TITLE
     , REVIEW_CONTENT
     , RATING
     , REVIEW_THUMBNAIL_ORIGIN 
     , REVIEW_THUMBNAIL_CHANGE
     , REVIEW_DATE
     , R.STATUS
     , R.PRODUCT_NO
     , R.MEMBER_ID
     , P.PRODUCT_NAME
     , p.PRODUCT_CHANGE
     , M.MEMBER_NAME
  FROM REVIEW R
  JOIN PRODUCT P ON R.PRODUCT_NO = P.PRODUCT_NO
  JOIN MEMBER M ON R.MEMBER_ID = M.MEMBER_ID
  
  
  
  
SELECT O.ORDER_DATE,
	       M.MEMBER_NAME,
	       PD.PRODUCT_NAME,
	       PD.PRODUCT_PRICE,
	       PD.PRODUCT_NO,
	       P.CANCEL_STATUS,
	       M.MEMBER_ID
	FROM PAYMENT P
	JOIN ORDER_TB O ON P.ORDER_IMPNO = O.ORDER_IMPNO
	JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
	JOIN PRODUCT PD ON PD.PRODUCT_NO = P.PRODUCT_NO
	ORDER BY O.ORDER_DATE DESC
    
    SELECT  
    O.ORDER_IMPNO,
    MAX(O.ORDER_NO) AS ORDER_NO,
    MAX(O.RECEIVER_NAME) AS RECEIVER_NAME,
    MAX(O.RECEIVER_PHONE) AS RECEIVER_PHONE,
    MAX(O.REQUEST_MSG) AS REQUEST_MSG,
    MAX(O.DELIVERY_DATE) AS DELIVERY_DATE,
    MAX(O.ORDER_STATUS) AS ORDER_STATUS,
    MAX(M.MEMBER_ID) AS MEMBER_ID,
    MAX(D.ADDRESS_NAME) AS ADDRESS_NAME,
    MAX(D.ADDRESS_OTHER) AS ADDRESS_OTHER
FROM ORDER_TB O
JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
JOIN DELIVERY_ADDRESS D ON D.MEMBER_ID = O.MEMBER_ID  
WHERE O.ORDER_IMPNO = 'imp_414059863069'
GROUP BY O.ORDER_IMPNO;



  SELECT  
			    O.ORDER_IMPNO,
			    MAX(O.ORDER_NO) AS ORDER_NO,
			    MAX(O.RECEIVER_NAME) AS RECEIVER_NAME,
			    MAX(O.RECEIVER_PHONE) AS RECEIVER_PHONE,
			    MAX(O.REQUEST_MSG) AS REQUEST_MSG,
			    MAX(O.DELIVERY_DATE) AS DELIVERY_DATE,
			    MAX(O.ORDER_STATUS) AS ORDER_STATUS,
			    MAX(M.MEMBER_ID) AS MEMBER_ID,
			    MAX(D.ADDRESS_NAME) AS ADDRESS_NAME,
			    MAX(D.ADDRESS_OTHER) AS ADDRESS_OTHER
			FROM ORDER_TB O
			JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
			JOIN DELIVERY_ADDRESS D ON D.MEMBER_ID = O.MEMBER_ID  
			GROUP BY O.ORDER_IMPNO;
            
    	    SELECT  
			    O.ORDER_IMPNO,
			    MAX(O.ORDER_NO) AS ORDER_NO,
			    MAX(O.RECEIVER_NAME) AS RECEIVER_NAME,
			    MAX(O.RECEIVER_PHONE) AS RECEIVER_PHONE,
			    MAX(O.REQUEST_MSG) AS REQUEST_MSG,
			    MAX(O.DELIVERY_DATE) AS DELIVERY_DATE,
			    MAX(O.ORDER_STATUS) AS ORDER_STATUS,
			    MAX(M.MEMBER_ID) AS MEMBER_ID,
			    MAX(D.ADDRESS_NAME) AS ADDRESS_NAME,
			    MAX(D.ADDRESS_OTHER) AS ADDRESS_OTHER
			FROM ORDER_TB O
			JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
			JOIN DELIVERY_ADDRESS D ON D.MEMBER_ID = O.MEMBER_ID  
			WHERE O.ORDER_NO = 30
			GROUP BY O.ORDER_IMPNO
            
    
SELECT ORDER_IMPNO
     , ORDER_NO
     , TOTAL_PRICE
     , RECEIVER_NAME
     , ORDER_STATUS
     , MEMBER_NAME
     , ORDER_DATE
  FROM ORDER_TB O
  JOIN MEMBER M ON O.MEMBER_ID = M.MEMBER_ID
  ORDER BY ORDER_NO DESC

SELECT ORDER_NO
     , M.MEMBER_NAME
     , M.PHONE
     , RECEIVER_NAME
     , RECEIVER_PHONE
     , REQUEST_MSG
  FROM ORDER_TB O
  JOIN MEMBER M ON O.MEMBER_ID = M.MEMBER_ID
 WHERE ORDER_NO = 33
 
ALTER TABLE ORDER_TB ADD ADDRESS VARCHAR2(300);
ALTER TABLE ORDER_TB ADD ADDRESS_ALIAS VARCHAR2(100);

commit;

SELECT ORDER_NO
     , M.MEMBER_NAME
     , M.PHONE
     , RECEIVER_NAME
     , RECEIVER_PHONE
     , ADDRESS_ALIAS
     , O.ADDRESS
     , REQUEST_MSG
     , TOTAL_PRICE
  FROM ORDER_TB O 
  JOIN MEMBER M ON O.MEMBER_ID = M.MEMBER_ID
 WHERE ORDER_NO = 36
 
 SELECT TRUNC(ENROLL_DATE, 'MM') - MOD(TO_NUMBER(TO_CHAR(ENROLL_DATE, 'MM')) - 1, 3) * INTERVAL '1' MONTH AS QUARTER_START,
	           COUNT(*) AS TOTAL
		  FROM MEMBER
		 GROUP BY TRUNC(ENROLL_DATE, 'MM') - MOD(TO_NUMBER(TO_CHAR(ENROLL_DATE, 'MM')) - 1, 3) * INTERVAL '1' MONTH
		 ORDER BY QUARTER_START
         
         
         
 SELECT  
    O.ORDER_IMPNO,
    MAX(O.ORDER_NO) AS ORDER_NO,
    MAX(O.RECEIVER_NAME) AS RECEIVER_NAME,
    MAX(O.RECEIVER_PHONE) AS RECEIVER_PHONE,
    MAX(O.REQUEST_MSG) AS REQUEST_MSG,
    MAX(O.DELIVERY_DATE) AS DELIVERY_DATE,
    MAX(O.ORDER_STATUS) AS ORDER_STATUS,
    MAX(M.MEMBER_ID) AS MEMBER_ID,
    MAX(D.ADDRESS_NAME) AS ADDRESS_ALIAS,
    MAX(D.ADDRESS_OTHER) AS ADDRESS_OTHER
FROM ORDER_TB O
JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
JOIN DELIVERY_ADDRESS D ON D.MEMBER_ID = O.MEMBER_ID  
WHERE O.ORDER_NO = 34
GROUP BY O.ORDER_IMPNO 

SELECT  
			    O.ORDER_IMPNO,
			    MAX(O.ORDER_NO) AS ORDER_NO,
			    MAX(O.RECEIVER_NAME) AS RECEIVER_NAME,
			    MAX(O.RECEIVER_PHONE) AS RECEIVER_PHONE,
			    MAX(O.REQUEST_MSG) AS REQUEST_MSG,
			    MAX(O.DELIVERY_DATE) AS DELIVERY_DATE,
			    MAX(O.ORDER_STATUS) AS ORDER_STATUS,
			    MAX(M.MEMBER_ID) AS MEMBER_ID,
			    MAX(D.ADDRESS_NAME) AS ADDRESS_NAME,
			    MAX(D.ADDRESS_OTHER) AS ADDRESS_OTHER,
                MAX(O.ORDER_DATE) AS ORDER_DATE
			FROM ORDER_TB O
			JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
			JOIN DELIVERY_ADDRESS D ON D.MEMBER_ID = O.MEMBER_ID  
			GROUP BY O.ORDER_IMPNO
            
  SELECT  
			    O.ORDER_IMPNO,
			    MAX(O.ORDER_NO) AS ORDER_NO,
			    MAX(O.RECEIVER_NAME) AS RECEIVER_NAME,
			    MAX(O.RECEIVER_PHONE) AS RECEIVER_PHONE,
			    MAX(O.REQUEST_MSG) AS REQUEST_MSG,
			    MAX(O.DELIVERY_DATE) AS DELIVERY_DATE,
			    MAX(O.ORDER_STATUS) AS ORDER_STATUS,
			    MAX(M.MEMBER_ID) AS MEMBER_ID,
			    MAX(D.ADDRESS_NAME) AS ADDRESS_NAME,
			    MAX(D.ADDRESS_OTHER) AS ADDRESS_OTHER,
                MAX(O.ORDER_DATE) AS ORDER_DATE
			FROM ORDER_TB O
			JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
			JOIN DELIVERY_ADDRESS D ON D.MEMBER_ID = O.MEMBER_ID  
			GROUP BY O.ORDER_IMPNO
            
SELECT COUNT(*)
FROM
(SELECT  
    O.ORDER_IMPNO,
    MAX(O.ORDER_NO) AS ORDER_NO,
    MAX(O.RECEIVER_NAME) AS RECEIVER_NAME,
    MAX(O.RECEIVER_PHONE) AS RECEIVER_PHONE,
    MAX(O.REQUEST_MSG) AS REQUEST_MSG,
    MAX(O.DELIVERY_DATE) AS DELIVERY_DATE,
    MAX(O.ORDER_STATUS) AS ORDER_STATUS,
    MAX(M.MEMBER_ID) AS MEMBER_ID,
    MAX(D.ADDRESS_NAME) AS ADDRESS_NAME,
    MAX(D.ADDRESS_OTHER) AS ADDRESS_OTHER,
    MAX(O.ORDER_DATE) AS ORDER_DATE
FROM ORDER_TB O
JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
JOIN DELIVERY_ADDRESS D ON D.MEMBER_ID = O.MEMBER_ID  
GROUP BY O.ORDER_IMPNO)


 INSERT INTO ORDER_TB (
        ORDER_NO, MEMBER_ID, RECEIVER_NAME, RECEIVER_PHONE,
        REQUEST_MSG, TOTAL_PRICE, ORDER_IMPNO, ORDER_DATE, ADDRESS, ADDRESS_ALIAS
    ) VALUES (
        ORDER_SEQ.NEXTVAL, 'user03', '고길동', '01029788728',
        null, 500, 'imp_273894912812', SYSDATE, '서울시 성동구 집앞', '집앞'
    )
 INSERT INTO PAYMENT (
	        ORDER_IMPNO,
	        PRODUCT_NO,
	        PRODUCT_COUNT,
	        CANCEL_STATUS,
	        CANCEL_REASON
	    ) VALUES (
	        'imp_273894912812',
	        14,
	        5,
	        '결제완료',
	        NULL
	    )
 INSERT INTO DELIVERY_ADDRESS (
	        ADDRESS_NO,
	        ADDRESS_NAME,
	        ADDRESS_OTHER,
	        IS_DEFAULT,
	        RECEIVER_NAME,
            RECEIVER_PHONE,
            MEMBER_ID
	    ) VALUES (
	        DELIVERY_ADDRESS_SEQ.NEXTVAL,
	        '집앞',
	        '서울시 성동구 집앞',
            'N',
	        '고길동',
            '01029788728',
            'user03'    
	    )
        
COMMIT;
COMMIT;
COMMIT;

SELECT  
    O.ORDER_IMPNO,
    MAX(O.ORDER_NO) AS ORDER_NO,
    MAX(O.RECEIVER_NAME) AS RECEIVER_NAME,
    MAX(O.RECEIVER_PHONE) AS RECEIVER_PHONE,
    MAX(O.REQUEST_MSG) AS REQUEST_MSG,
    MAX(O.DELIVERY_DATE) AS DELIVERY_DATE,
    MAX(O.ORDER_STATUS) AS ORDER_STATUS,
    MAX(M.MEMBER_ID) AS MEMBER_ID,
    MAX(D.ADDRESS_NAME) AS ADDRESS_NAME,
    MAX(D.ADDRESS_OTHER) AS ADDRESS_OTHER
FROM ORDER_TB O
JOIN MEMBER M ON M.MEMBER_ID = O.MEMBER_ID
JOIN DELIVERY_ADDRESS D ON D.MEMBER_ID = O.MEMBER_ID  
WHERE O.ORDER_NO = 48
GROUP BY O.ORDER_IMPNO;
            
SELECT P.PRODUCT_CHANGE,
       P.PRODUCT_NAME,
       C.PRODUCT_COUNT,
       P.PRODUCT_PRICE
  FROM PRODUCT P
  JOIN CART C ON C.PRODUCT_NO = P.PRODUCT_NO
  JOIN ORDER_TB O ON O.MEMBER_ID = C.MEMBER_ID
  WHERE ORDER_NO= 48
            
		SELECT ORDER_NO
		     , M.MEMBER_NAME
		     , M.PHONE
		     , RECEIVER_NAME
		     , RECEIVER_PHONE
		     , ADDRESS_ALIAS
		     , O.ADDRESS
		     , REQUEST_MSG
		     , TOTAL_PRICE
		  FROM ORDER_TB O 
		  JOIN MEMBER M ON O.MEMBER_ID = M.MEMBER_ID
		 WHERE ORDER_NO = 40
         COMMIT

ALTER TABLE PAYMENT ADD(PRODUCT_SIZE CHAR(1))
ALTER TABLE ORDER_TB DROP (PRODUCT_COUNT, PRODUCT_SIZE, PRODUCT_NO);
ALTER TABLE ORDER_TB
ADD CONSTRAINT FK_ORDER_PRODUCT_SIZE
FOREIGN KEY (PRODUCT_NO, PRODUCT_SIZE)
REFERENCES PRODUCT_SIZE (PRODUCT_NO, PRODUCT_SIZE);


UPDATE PRODUCT_SIZE
  SET STOCK_COUNT = STOCK_COUNT - 2
 WHERE PRODUCT_NO = 12
   AND PRODUCT_SIZE = 'M'
   
DELETE 
  FROM CART
 WHERE MEMBER_ID =  ?
   AND PRODUCT_NO = ?
   AND PRODUCT_SIZE =  
   ?
   
SELECT NVL((
    SELECT STOCK_COUNT
     FROM PRODUCT_SIZE
    WHERE PRODUCT_NO = 17 
      AND PRODUCT_SIZE = 'S'
), 0) AS COUNT
FROM DUAL


SELECT ORDER_NO
     , RECEIVER_NAME
     , RECEIVER_PHONE
     , ORDER_DATE
     , ORDER_STATUS
  FROM ORDER_TB
 WHERE ORDER_STATUS = '배송전'

SELECT ORDER_NO
     , MEMBER_NAME
     , TOTAL_PRICE
     , ORDER_DATE
     , ORDER_STATUS
     , CANCEL_STATUS
  FROM ORDER_TB O
  JOIN MEMBER M ON O.MEMBER_ID = M.MEMBER_ID
  JOIN (
    SELECT ORDER_IMPNO
        , MAX(CANCEL_STATUS) AS CANCEL_STATUS
    FROM PAYMENT 
    GROUP BY ORDER_IMPNO 
    ) P ON P.ORDER_IMPNO = O.ORDER_IMPNO
    
SELECT ORDER_NO
     , ORDER_IMPNO
     , RECEIVER_NAME
     , RECEIVER_PHONE
     , O.ADDRESS
     , REQUEST_MSG
     , MEMBER_NAME
     , PHONE
  FROM ORDER_TB O
  JOIN MEMBER M ON O.MEMBER_ID = M.MEMBER_ID
 WHERE ORDER_NO = 30
 

SELECT ORDER_IMPNO
     , P.PRODUCT_NO
     , PRODUCT_NAME
     , PRODUCT_PRICE
     , PRODUCT_COUNT
     , PRODUCT_CHANGE
  FROM PAYMENT P
  JOIN PRODUCT PT ON P.PRODUCT_NO = PT.PRODUCT_NO
  WHERE ORDER_IMPNO = 'imp_686057229069'
    AND P.PRODUCT_NO = 26
    
SELECT PRODUCT_NO
     , O.ORDER_IMPNO
  FROM ORDER_TB O
  JOIN PAYMENT P ON O.ORDER_IMPNO = P.ORDER_IMPNO
 WHERE ORDER_NO = 59
 

UPDATE ORDER_TB
   SET DELIVERY_DATE = SYSDATE
 WHERE ORDER_NO = 63
commit

	UPDATE ORDER_TB
	   SET ORDER_STATUS = '배송완료', DELIVERY_DATE = SYSDATE
	 WHERE ORDER_NO = 65
     COMMIT
     
    	 	SELECT ORDER_NO
		     , MEMBER_NAME
		     , TOTAL_PRICE
		     , ORDER_DATE
		     , ORDER_STATUS
		     , CANCEL_STATUS
		  FROM ORDER_TB O
		  JOIN MEMBER M ON O.MEMBER_ID = M.MEMBER_ID
		  left JOIN (
		    SELECT ORDER_IMPNO
		        , MAX(CANCEL_STATUS) AS CANCEL_STATUS
		    FROM PAYMENT 
		    GROUP BY ORDER_IMPNO 
		    ) P ON P.ORDER_IMPNO = O.ORDER_IMPNO
		   ORDER BY ORDER_NO DESC
           
           
	   SELECT *
	   FROM
	   (
	   SELECT ROWNUM RNUM, A.*
	   FROM (
			   SELECT ORDER_NO
			   		, ORDER_DATE
			   		, ORDER_STATUS
                    , CANCEL_STATUS
                    , TOTAL_PRICE
                    , MEMBER_NAME
				  FROM ORDER_TB O
                  JOIN MEMBER M ON O.MEMBER_ID = M.MEMBER_ID
                  LEFT JOIN (
                    SELECT ORDER_IMPNO
                        , MAX(CANCEL_STATUS) AS CANCEL_STATUS
                    FROM PAYMENT 
                    GROUP BY ORDER_IMPNO 
                    ) P ON P.ORDER_IMPNO = O.ORDER_IMPNO
                         WHERE ORDER_STATUS = '주문완료'
                         ORDER BY ORDER_NO DESC
				  ) A
			)
			WHERE RNUM BETWEEN 1 AND 10
            
            
SELECT SUM(TOTAL_PRICE)
  FROM ORDER_TB
  
   		SELECT COUNT(*)
 		FROM MEMBER
 		WHERE GENDER = 'M'